package Tables;
// Generated 12-feb-2016 8:38:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auxdep generated by hbm2java
 */
public class Auxdep  implements java.io.Serializable {


     private byte deptNo;
     private String dnombre;
     private String loc;
     private Set<?> auxemps = new HashSet<Object>(0);

    public Auxdep() {
    }

	
    public Auxdep(byte deptNo) {
        this.deptNo = deptNo;
    }
    public Auxdep(byte deptNo, String dnombre, String loc, Set<?> auxemps) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
       this.auxemps = auxemps;
    }
   
    public byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(byte deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set<?> getAuxemps() {
        return this.auxemps;
    }
    
    public void setAuxemps(Set<?> auxemps) {
        this.auxemps = auxemps;
    }




}


