package Tables;
// Generated 12-feb-2016 8:38:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Auxemp generated by hbm2java
 */
public class Auxemp  implements java.io.Serializable {


     private int empNo;
     private Departamentos auxdep;
     private String apellido;
     private String oficio;
     private Integer dir;
     private Date fechaAlta;
     private Double salario;
     private Double comision;

    public Auxemp() {
    }

	
    public Auxemp(int empNo) {
        this.empNo = empNo;
    }
    public Auxemp(int empNo, Departamentos auxdep, String apellido, String oficio, Integer dir, Date fechaAlta, Double salario, Double comision) {
       this.empNo = empNo;
       this.auxdep = auxdep;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.comision = comision;
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public Departamentos getAuxdep() {
        return this.auxdep;
    }
    
    public void setAuxdep(Departamentos auxdep) {
        this.auxdep = auxdep;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Integer getDir() {
        return this.dir;
    }
    
    public void setDir(Integer dir) {
        this.dir = dir;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Double getComision() {
        return this.comision;
    }
    
    public void setComision(Double comision) {
        this.comision = comision;
    }




}


