
package Menu;

import MisOpciones.OpcionDepartamentos;
import MisOpciones.OpcionEmpleados;
import Tables.SessionFactoryUtil;
import javax.swing.JOptionPane;
import org.hibernate.SessionFactory;

/**
 *
 * @author CrisRodFe
 */
public class JDialogConsultas extends javax.swing.JDialog {

    
    private static final SessionFactory sesion = SessionFactoryUtil.getSessionFactory();
    private OpcionDepartamentos od = new OpcionDepartamentos();
    private OpcionEmpleados oe = new OpcionEmpleados();
    
    /**
     * Creates new form JDialogConsultas
     */
    public JDialogConsultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldNumero.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonTotal = new javax.swing.JRadioButton();
        jRadioButtonTotalD = new javax.swing.JRadioButton();
        jTextFieldNumero = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsulta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(jRadioButtonTotal);
        jRadioButtonTotal.setText("Total, media y salario máximo de la empresa");
        jRadioButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTotalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTotalD);
        jRadioButtonTotalD.setText("Total, media y salario máximo del departamento nº:");
        jRadioButtonTotalD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTotalDActionPerformed(evt);
            }
        });

        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyPressed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jTextAreaConsulta.setColumns(20);
        jTextAreaConsulta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonTotalD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonTotal))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTotalD)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Muestra las diferentes consultas en el área de texto.
     * 
     * Si la consulta es sobre un departamento primero se comprueba si:
     * - se ha introducido un departamento.
     * - si el departamento existe
     * Se envía un mensaje de información al usuario si falla alguna comprobación.
     * @param evt 
     */
    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        if(jRadioButtonTotal.isSelected())
        {
            jTextAreaConsulta.setText(String.format("%-13s%-13s%-13s\n\n","MEDIA","MAXIMO","SUMATORIO"));
            jTextAreaConsulta.append(oe.getInfoSalarios(sesion));
        }   
        
        if(jRadioButtonTotalD.isSelected())
        {
            if(jTextFieldNumero.getText().equals(""))//Si el campo está vacío mostramos un mensaje 
            {
                JOptionPane.showMessageDialog(rootPane, "Debe introducir un nº de departamento");
            }
            else
            {    
                byte deptNo = Byte.parseByte(jTextFieldNumero.getText());
                if(od.existeDepartamento(sesion, deptNo))
                {    
                    jTextAreaConsulta.setText(String.format("%-13s%-13s%-13s\n\n","MEDIA","MAXIMO","SUMATORIO"));
                    jTextAreaConsulta.append(oe.getInfoSalariosDept(sesion,deptNo));
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "El departamento no existe.");
                }
            } 
        }    
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jRadioButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTotalActionPerformed
        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.setText("");
        jTextAreaConsulta.setText("");
    }//GEN-LAST:event_jRadioButtonTotalActionPerformed

    private void jRadioButtonTotalDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTotalDActionPerformed
        jTextFieldNumero.setEnabled(true);
        jTextAreaConsulta.setText("");
    }//GEN-LAST:event_jRadioButtonTotalDActionPerformed

    private void jTextFieldNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyPressed
       jTextAreaConsulta.setText("");
    }//GEN-LAST:event_jTextFieldNumeroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogConsultas dialog = new JDialogConsultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JRadioButton jRadioButtonTotal;
    private javax.swing.JRadioButton jRadioButtonTotalD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConsulta;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
